name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Supported LTS and current
        node: ['22.x', '24.x', '26.x']
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
  pre-commit:
    name: Pre-Commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - uses: andrewaylett/pre-commit-action@57a149d3daa51e633e2717e245fd508db4682461 # v4
      env:
        SKIP: npm-dedupe,npm-lint
